# Al-Driven Enrollment Forecasting & Resource Optimization

## In this, we will create a real world balance dataset using python library "faker"

In [1]:
import pandas as pd
import random
from faker import Faker

In [2]:
fake=Faker()

In [3]:
# sample one row
record = {
    "course_id": random.randint(100, 200),
    "tuition_fee": random.randint(20000, 100000),
    "waitlist": random.randint(0, 50),
    "retention_rate": round(random.uniform(0.5, 0.95), 2),
    "feedback_score": round(random.uniform(1, 5), 1),
    "faculty_rating": round(random.uniform(2, 5), 1),
    "capacity": random.randint(30, 120),
    "enrollment": random.randint(20, 120)
}

print(record)

{'course_id': 186, 'tuition_fee': 86466, 'waitlist': 2, 'retention_rate': 0.76, 'feedback_score': 4.0, 'faculty_rating': 2.4, 'capacity': 37, 'enrollment': 83}

In [4]:
data = []

for _ in range(5000):
    capacity = random.randint(30, 120)
    waitlist = random.randint(0, 50)
    retention_rate = round(random.uniform(0.5, 0.95), 2)
    feedback_score = round(random.uniform(1, 5), 1)
    
    # ✅ DEFINE FIRST
    faculty_rating = round(random.uniform(2, 5), 1)

    # ✅ THEN USE IT
    enrollment = int(
        0.6 * capacity +
        1.0 * waitlist +
        20 * retention_rate +
        10 * feedback_score +
        8 * faculty_rating +
        random.randint(-3, 3)
    )

    record = {
        "course_id": random.randint(100, 200),
        "tuition_fee": random.randint(20000, 100000),
        "waitlist": waitlist,
        "retention_rate": retention_rate,
        "feedback_score": feedback_score,
        "faculty_rating": faculty_rating,  # reuse variable
        "capacity": capacity,
        "enrollment": max(0, enrollment)
    }

    data.append(record)

In [5]:
df = pd.DataFrame(data)
df.head()

,course_id,tuition_fee,waitlist,retention_rate,feedback_score,faculty_rating,capacity,enrollment
0,162,89376,40,0.53,4.8,2.2,91,167
1,144,75562,10,0.52,2.7,2.2,100,127
2,190,47862,33,0.67,1.1,3.1,101,145
3,149,42159,47,0.84,5.0,4.6,59,185
4,107,35966,49,0.81,3.5,2.6,63,160

In [6]:
df.to_csv("../data/enrollment_data.csv", index=False)

In [7]:
df.describe()
df.corr()

,course_id,tuition_fee,waitlist,retention_rate,feedback_score,faculty_rating,capacity,enrollment
course_id,1.000000,-0.031206,-0.018755,-0.008598,0.024195,0.003632,0.010891,0.005483
tuition_fee,-0.031206,1.000000,0.013800,0.004348,0.000350,0.003329,0.015972,0.019959
waitlist,-0.018755,0.013800,1.000000,0.000477,0.015541,-0.008969,-0.000302,0.576172
retention_rate,-0.008598,0.004348,0.000477,1.000000,-0.005934,-0.000909,-0.022512,0.084500
feedback_score,0.024195,0.000350,0.015541,-0.005934,1.000000,0.022978,0.001043,0.462691
faculty_rating,0.003632,0.003329,-0.008969,-0.000909,0.022978,1.000000,0.003993,0.274932
capacity,0.010891,0.015972,-0.000302,-0.022512,0.001043,0.003993,1.000000,0.612163
enrollment,0.005483,0.019959,0.576172,0.084500,0.462691,0.274932,0.612163,1.000000